//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ListVersion
{
	public virtual DateTime CreateDateTime
	{
		get;
		set;
	}

	public virtual IEnumerable<ListItem> ListItems
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual ListVersionState State
	{
		get;
		set;
	}

}

