//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ListSecurity
{
	public virtual ListRole Role
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual ListRole ListRole
	{
		get;
		set;
	}

}

