//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual string UserName
	{
		get;
		set;
	}

	public virtual string FirstName
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string Password
	{
		get;
		set;
	}

	public virtual DateTime LastLogin
	{
		get;
		set;
	}

	public virtual IEnumerable<SiteRole> Roles
	{
		get;
		set;
	}

	public virtual IEnumerable<SiteRole> SiteRole
	{
		get;
		set;
	}

}

